### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/OpenReq#5]
Hi,
I'm sorry for opening an issue here, but I'm not sure in which sub-project to report this issue:
The certificate of https://api.openreq.eu/ is expired.

**Comment by VolodymyrBiryuk** [comment]
An issue was opened on Tuleap. Thank you.

**Comment by dfucci** [comment]
Hi @AndreaMussmann, thanks for reporting. We installed the new certificates which should be available soon.
