### ISSUE TITLE
Question about api.openreq.eu

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/OpenReq#6]
I would like to know if the micro services at api.openreq.eu will be updated to the most recent service versions (as seen in github), in particular prs-improving-requirement-quality (returns 502 at the moment), similarity-detection (api outdated, cannot be used), and requirements-classifier.

Thanks.

**Comment by dfucci** [comment]
Hi @AndreaMussmann 
this should be the case, as GitHub is hooked to the deployment server where the microservices are available.

For the specific microservices, the persons mentioned in this issue should be able to assist you:
- prs-improving-requirement-quality @claudiareng
- similarity-detection @quim-motger 
- requirements-classifier @quim-motger

**Comment by LloydThinks** [comment]
Hi @AndreaMussmann 

As mentioned by @dfucci , the deployment infrastructure is hooked up to the master branches of GitHub, so the microservices should always be available. There are, at times, temporary issues with the deployment server. We apologize for the downtime and are always working to keep our services live.

I'm closing this issue as any additional issues can be opened as a separate ticket. The issues described here should not be persistent.

Lloyd
